version: '3'

services:
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent-complete:8.1.1
    container_name: elastic-agent
    restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      # - FLEET_ENROLLMENT_TOKEN=R1M3N3ozOEJuUHk5NjM1VFJCUWg6T090YzRRZlRUWFdiUXctQUE5a19DUQ==
      # - FLEET_ENROLL=1
      - FLEET_URL=https://es01:8220
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://es01:9200
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDg0NTk1MzAwMjI6QW5XNTZjZXpTWEtZN0g0TXZNZ0NpUQ
      - FLEET_SERVER_ELASTICSEARCH_USERNAME=elastic
      - FLEET_SERVER_ELASTICSEARCH_PASSWORD=*-ITEeu2+Y1RhSzrg+G4
      - ELASTICSEARCH_HOST=https://es01:9200
      - ELASTICSEARCH_CA=/usr/share/elastic-agent/http_ca.crt
      - ELASTICSEARCH_USERNAME=elastic 
      - ELASTICSEARCH_PASSWORD=*-ITEeu2+Y1RhSzrg+G4
      - KIBANA_FLEET_SETUP=1 
      - KIBANA_HOST=https://kibana:5601 
      - KIBANA_CA=/usr/share/elastic-agent/ca_1648446623684.crt
      - KIBANA_USERNAME=elastic 
      - KIBANA_PASSWORD=*-ITEeu2+Y1RhSzrg+G4
    volumes:
      - ./data/http_ca.crt:/usr/share/elastic-agent/http_ca.crt:ro
      - ./data/ca_1648446623684.crt:/usr/share/elastic-agent/ca_1648446623684.crt:ro
    networks:
      - elastic
      
networks:
  elastic:
    external: true