#!/bin/bash

POSTGRES_USER=postgres 
POSTGRES_PASSWORD=SuperSecret

PGADMIN_DEFAULT_EMAIL="user@example.com"
PGADMIN_DEFAULT_PASSWORD=Somerandompassword

PGSQL_CONTAINER_NAME=postgresql
PGADSMIN_CONTAINER_NAME=pgadmin

postgres_preflight_check() {
   docker volume create pgdata
}
pgadmin_preflight_check() {
    docker volume create pgamdin
}

start_postgres() {
    echo "Starting PostgreSQL container now....."
    docker run -d --name $PGSQL_CONTAINER_NAME \
        --add-host "host.docker.internal:host-gateway" \
        -v pgdata:/var/lib/postgresql/data \
        -p 5432:5432 \
        -e POSTGRES_USER=$POSTGRES_USER \
        -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
        postgres:17-bullseye
}

start_pgadmin() {
    echo "Starting PGAdmin container now....."
    docker run -d --name $PGADSMIN_CONTAINER_NAME -p 80:80 \
        --add-host "host.docker.internal:host-gateway" \
        -v pgamdin:/var/lib/pgadmin \
        -e PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL \
        -e PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD \
        dpage/pgadmin4:8.12.0       
}

stop_postgres() {
    echo "Stopping PostgreSQL container now....."
    docker container stop $PGSQL_CONTAINER_NAME
    docker container rm $PGSQL_CONTAINER_NAME
}

stop_pgadmin() {
    echo "Stopping PGAdmin container now....."
    docker container stop $PGADSMIN_CONTAINER_NAME
    docker container rm $PGADSMIN_CONTAINER_NAME
}

delete_postgres() {
    echo "Deleting PostgreSQL container now....."
    stop_postgres
    docker volume rm pgdata   
}

delete_pgadmin() {
    echo "Deleting PGAdmin container now....."
    stop_pgadmin
    docker volume rm pgamdin       
}

# check if command line argument is empty or not present
if [ -z $1 ]; 
then
    echo "No arguement provided to determine to start/stop/delete the container"
    exit 0
fi

case "$1" in
    "stop")
        stop_pgadmin
        stop_postgres ;;
    "start")
        postgres_preflight_check
        pgadmin_preflight_check    
        start_postgres
        start_pgadmin ;;
    "delete")
        delete_postgres
        delete_pgadmin ;;
esac
