#!/bin/bash

# check if command line argument is empty or not present
if [ -z $1 ]; 
then
    echo "No arguement provided to determine to start/stop the container"
    exit 0
fi

docker network create database

case "$1" in
    "down")
        docker compose -f postgresql-docker-compose.yml down ;;
    "up")
        docker compose -f postgresql-docker-compose.yml up -d --no-recreate ;;
esac

