#!/bin/bash

# For using port forwarding option
export ARGOCD_OPTS='--port-forward-namespace argocd'

# get initial password for admin user
kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
