version: "3.9"

# -------------- Networks -------------- 
networks:
  stream_sql_demo:
    external: true


# -------------- Volumes -------------- 
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local 

# -------------- Services -------------- 
services:

  # -------------- zookeeper service -------------- 
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - stream_sql_demo

  # -------------- kafka service -------------- 
  kafka:
    image: docker.io/bitnami/kafka:3.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9094,OUTSIDE://localhost:9092
      - KAFKA_LISTENERS=INSIDE://:9094,OUTSIDE://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      #- KAFKA_CREATE_TOPICS="user_behavior:1:1"
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - stream_sql_demo
    # command: 
    #   [ "/bin/bash", 
    #   "-c", 
    #   "sleep 60; cd /opt/bitnami/kafka; ./bin/kafka-topics.sh --create --topic \"user_behavior\" --replication-factor 1 --partitions 1 --bootstrap-server kafka:9092"]