version: '3.6'
services:
  runner:
    image: 'gitlab/gitlab-runner:latest'
    container_name: gitlab-runner
    restart: always
    hostname: '10.0.0.7'
    # env_file:
    #   - .env    
    environment:
      REGISTRATION_TOKEN: |
        $GITLAB_RUNNER_REGISTRATION_TOKEN   
    command: |
      sh -c '/register-runner.sh'
    volumes:
      - '$GITLAB_HOME/gitlab-runner/config:/etc/gitlab-runner'
      - ./scripts/register-runner.sh:/register-runner.sh

