groups:
  - docker

users:
  - default
  - name: ubuntu
    gecos: Ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    shell: /bin/bash
    ssh_import_id: None
    lock_passwd: true
    ssh_authorized_keys:
      - <ssh-public-keys>
package_update: true
package_upgrade: true
packages:
  - [ca-certificates, curl, gnupg, git, avahi-daemon]


