groups:
  - docker

users:
  - default
  - name: ubuntu
    gecos: Ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    shell: /bin/bash
    ssh_import_id: None
    lock_passwd: true
    ssh_authorized_keys:
      - <ssh-public-key>
package_update: true
package_upgrade: true
packages:
  - [avahi-daemon, apt-transport-https, ca-certificates, curl, gnupg, lsb-release, git, uidmap, dbus-user-session]
runcmd:
  - sudo curl -fsSL https://get.docker.com | sudo /bin/bash
  - sudo systemctl enable docker.service
  - sudo systemctl enable containerd.service
