#!/bin/bash

PATH_DATASET=/datasets
PATH_NOTEBOOK=/notebooks
PATH_GIT_REPO=/repo

HOST_DATASET_PATH=${HOME}/Projects/work/datasets

docker run -it --name anaconda --mount type=bind,source=${HOST_DATASET_PATH},target=${PATH_DATASET} -p 8888:8888 continuumio/anaconda3:2021.11 \
    /bin/bash -c "
        conda install jupyter -y --quiet && \
        mkdir -p ${PATH_NOTEBOOK} && \
        mkdir -p ${PATH_GIT_REPO} && \
        jupyter notebook \
        --notebook_dir=${PATH_NOTEBOOK} --ip='*' --port=8888 \
        --no-browser --allow-root
    "